"""
Task 2 — the LamarCy sprite. IDLE pose (draft, for Durrell's approval).

The figure: wide-brim hat with a Tiffany band, short ink beard, dark jacket
over a good cream shirt (three buttons, open collar), deep-teal skin, and an
acoustic guitar standing upright at his side, hand resting on the neck —
an elder portrait, not an action hero. Original silhouette; resembles
nobody's mascot.

Canvas decision: 48×48 native (not 32×48). The figure alone is ~19px wide,
but the guitar at his side needs the extra columns, and keeping EVERY pose
and creature frame on the same 48×48 canvas makes sprite sheets and the
Studio app dead simple. Documented here so future-me knows it was a choice.

Grid codes (see pixel.py): . transparent · K ink · D deep teal · T tiffany
· C cream (or harbor sepia in the sepia ramp).

Run:  python3 brand/8bit/src/sprite_lamarcy.py
Out:  brand/8bit/sprites/lamarcy/{teal,sepia}/idle@{1,4,8}x.png
"""

from pixel import EIGHTBIT, parse_grid, save_sprite

# ruler:  012345678901234567890123456789012345678901234567
#                   1111111111222222222233333333334444444444
IDLE = """
................................................
......................KKKKKKKKKKK...............
.....................KKKKKKKKKKKKK..............
.....................KKKKKKKKKKKKK..............
.....................KKKKKKKKKKKKK..............
.....................KTTTTTTTTTTTK..............
................KKKKKKKKKKKKKKKKKKKKKKK.........
...................KKKKKKKKKKKKKKKKK............
.....................KDDDDDDDDDDDK..............
.....................KDDDDDDDDDDDK..............
.....................KDDKKDDDKKDDK..............
............KKKK.....KDDKKDDDKKDDK..............
............KTTK.....KDDDDDDDDDDDK..............
...........DKTTK.....KDDDDDKDDDDDK..............
............KTTK.....KKDDDKKKDDDKK..............
...........DKTTK.....KKKKKKKKKKKKK..............
............KKKK........KDDDDDK.................
.............KDK...KKKKKKKDDDKKKKKKK............
.............KCK...KKKKKCCCKCCCKKKKK............
.............KDKKKKKKKKKCCCCCCCKKKKK............
.............KKKK..KKKKKCCCKCCCKKKKK............
...........KDDDDK..KKKKKCCCCCCCKKKKK............
...........KDDDDK..KKKKKCCCCCCCKKKKK............
............KKDK...KKKKKCCCKCCCKKKKK............
.............KCK...KKKKKCCCCCCCKKKKK............
.............KDK...KKKKKCCCCCCCKKKKK............
.............KDK...KKKKKCCCKCCCKKKKD............
.............KCK...KKKKKCCCCCCCKKKKD............
.............KDK...KKKKKCCCCCCCKKKKD............
.............KDK...KKKKKCCCCCCCKKKKK............
..........KKKKKKKK.KKKKKKKKTKKKKKKKK............
.........KTTTTDTTTK.KKKKKKKKKKKKKKK.............
.........KTTTKDKTTK.KKKKKKKKKKKKKKK.............
.........KTTTKDKTTK.KKKKKKKKKKKKKKK.............
..........KTTKDKTK..KKKKKKKKKKKKKKK.............
..........KTTTDTTK..KKKKKKKKKKKKKKK.............
........KTTTTTDTTTTK.KKKKKK.KKKKKK..............
........KTTTTTDTTTTK.KKKKKK.KKKKKK..............
........KTTTCCCCCTTK.KKKKKK.KKKKKK..............
........KTTTTTTTTTTK.KKKKKK.KKKKKK..............
........KTTTTTTTTTTK.KKKKKK.KKKKKK..............
........KTTTTTTTTTTK.KKKKKK.KKKKKK..............
........KTTTTTTTTTTK.KKKKKK.KKKKKK..............
.........KTTTTTTTTK.KKKKKKK.KKKKKKK.............
..........KTTTTTTK..KKKKKKK.KKKKKKK.............
...........KKKKKK...KKKKKKK.KKKKKKK.............
................................................
................................................
"""


def main() -> None:
    rows = parse_grid(IDLE)
    assert len(rows) == 48, f"expected 48 rows, got {len(rows)}"
    assert len(rows[0]) == 48, f"expected 48 cols, got {len(rows[0])}"
    save_sprite(rows, EIGHTBIT / "sprites" / "lamarcy", "idle")
    print("wrote brand/8bit/sprites/lamarcy/{teal,sepia}/idle@{1,4,8}x.png")


if __name__ == "__main__":
    main()
